const mongoose = require('mongoose');
const projectSchema = new mongoose.Schema({
  name: { type: String, required: true, trim: true },
  domain: { type: String, lowercase: true, trim: true, default: '' },
  description: { type: String, default: '' },
  projectType: { type: String, enum: ['software', 'design', 'business', 'content', 'research'], default: 'software' },
  status: { type: String, enum: ['on_track', 'at_risk', 'delayed', 'ready_to_test', 'completed'], default: 'on_track' },
  phase: { type: String, enum: ['discovery', 'planning', 'development', 'testing', 'review', 'launched', 'delivered', 'designing', 'prototyping', 'business_growth', 'validation', 'content_creation', 'editing', 'research', 'analysis'], default: 'planning' },
  progress: { type: Number, default: 0, min: 0, max: 100 },
  deadline: { type: Date },
  startDate: { type: Date, default: Date.now },
  client: { type: String, default: '' },
  techStack: [{ type: String }],
  repositories: [{ url: String, label: String }],
  githubRepo: { type: String, default: '' },
  teamChannel: { type: String, default: '' },
  teamsTeamId: { type: String, default: '' },
  teamsChannelId: { type: String, default: '' },
  members: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
  tasks: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Task' }],
  launchedAt: { type: Date },
  deliveredAt: { type: Date },
  deliveryNotes: { type: String, default: '' },
  isActive: { type: Boolean, default: true },
  settings: {
    priority: { type: String, enum: ['low', 'medium', 'high', 'urgent'], default: 'medium' },
    color: { type: String, default: '#2347e8' },
    clientName: { type: String, default: '' },
    frontendRepo: { type: String, default: '' },
    backendRepo: { type: String, default: '' },
    databaseRepo: { type: String, default: '' },
    mobileRepo: { type: String, default: '' },
    apiDocsUrl: { type: String, default: '' },
    stagingUrl: { type: String, default: '' },
    productionUrl: { type: String, default: '' },
    sprintDuration: { type: Number, default: 14 },
    sprintNamingConvention: { type: String, default: 'Sprint {n}' },
    storyPointsEnabled: { type: Boolean, default: false },
    enableAutoPhaseProgression: { type: Boolean, default: true },
    notifyTaskAssignment: { type: Boolean, default: true },
    notifySprintChanges: { type: Boolean, default: true },
    notifyProjectUpdates: { type: Boolean, default: true },
    emailNotifications: { type: Boolean, default: true },
    inAppNotifications: { type: Boolean, default: true },
    canCreateTasks: { type: String, enum: ['admin', 'project_manager', 'team_lead', 'developer'], default: 'developer' },
    canCreateSprints: { type: String, enum: ['admin', 'project_manager', 'team_lead'], default: 'team_lead' },
    canUploadFiles: { type: String, enum: ['admin', 'project_manager', 'team_lead', 'developer'], default: 'developer' },
    canEditSettings: { type: String, enum: ['admin', 'project_manager'], default: 'project_manager' },
    canDeleteResources: { type: String, enum: ['admin', 'project_manager', 'team_lead'], default: 'team_lead' },
    blockers: [{ type: String }],
    risks: [{ type: String }],
    issues: [{ type: String }],
    dependencies: [{ type: String }],
    healthNotes: { type: String, default: '' },
    isArchived: { type: Boolean, default: false },
    archivedAt: { type: Date },
    restoredAt: { type: Date },
  },
}, { timestamps: true });
projectSchema.index({ domain: 1 });
module.exports = mongoose.model('Project', projectSchema);
