const mongoose = require('mongoose');

const stepSchema = new mongoose.Schema({
  order: { type: Number, required: true },
  description: { type: String, required: true },
  expectedResult: { type: String, default: '' },
  actualResult: { type: String, default: '' },
  status: { type: String, enum: ['pending', 'pass', 'fail', 'blocked'], default: 'pending' },
  evidence: { type: String, default: '' },
}, { _id: true });

const testCaseSchema = new mongoose.Schema({
  testCaseId: { type: String },
  title: { type: String, required: true, trim: true },
  description: { type: String, default: '' },
  feature: { type: String, default: '' },
  type: {
    type: String,
    enum: ['integration', 'unit', 'e2e', 'security', 'performance', 'manual'],
    default: 'manual',
  },
  priority: {
    type: String,
    enum: ['low', 'medium', 'high', 'urgent', 'critical'],
    default: 'medium',
  },
  status: {
    type: String,
    enum: ['draft', 'ready', 'in_progress', 'passed', 'failed', 'blocked', 'skipped', 'retesting', 'auto-draft'],
    default: 'draft',
  },
  precondition: { type: String, default: '' },
  steps: [stepSchema],
  project: { type: mongoose.Schema.Types.ObjectId, ref: 'Project', required: true },
  sprint: { type: mongoose.Schema.Types.ObjectId, ref: 'Sprint' },
  assignee: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  linkedTask: { type: mongoose.Schema.Types.ObjectId, ref: 'Task' },
  linkedBug: { type: mongoose.Schema.Types.ObjectId, ref: 'Task' },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  executedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  executedAt: { type: Date },
  failureReason: { type: String, default: '' },
  attachments: [{
    filename: String,
    originalName: String,
    path: String,
    mimeType: String,
    uploadedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    uploadedAt: { type: Date, default: Date.now },
  }],
  tags: [{ type: String }],
  isActive: { type: Boolean, default: true },
  interestMatchScore: { type: Number, default: 100, min: 0, max: 100 },
  interestMatchStatus: { type: String, enum: ['high', 'low', 'flagged'], default: 'high' },
  flaggedForDeletion: { type: Boolean, default: false },
  flaggedAt: { type: Date },
  autoDeleteAt: { type: Date },
  autoGenerated: { type: Boolean, default: false },
  lastRunAt: { type: Date },
}, { timestamps: true });

testCaseSchema.pre('save', async function (next) {
  if (!this.testCaseId) {
    const Counter = mongoose.model('Counter');
    const TestCase = mongoose.model('TestCase');
    let attempts = 0;
    while (attempts < 100) {
      const counter = await Counter.findOneAndUpdate(
        { model: 'TestCase', field: 'testCaseId', reference: this.project },
        { $inc: { count: 1 } },
        { new: true, upsert: true },
      );
      this.testCaseId = `TC-${String(counter.count).padStart(3, '0')}`;
      const exists = await TestCase.findOne({ project: this.project, testCaseId: this.testCaseId }).lean();
      if (!exists) break;
      attempts++;
    }
  }
  next();
});

testCaseSchema.index({ project: 1, status: 1 });
testCaseSchema.index({ project: 1, testCaseId: 1 }, { unique: true });

module.exports = mongoose.model('TestCase', testCaseSchema);