const { Router } = require('express');
const { getProjects, getProjectById, createProject, updateProject, deleteProject, getProjectAnalytics, markLaunched, markDelivered, createTeamsChannel, evaluatePhase } = require('../controllers/projectController');
const settingsController = require('../controllers/settingsController');
const { auth, authorize } = require('../middleware/auth');
const resourceController = require('../controllers/resourceController');
const teamController = require('../controllers/teamController');
const teamGroupController = require('../controllers/teamGroupController');
const analyticsController = require('../controllers/analyticsController');
const upload = require('../middleware/upload');
const router = Router();
router.use(auth);
router.get('/', getProjects);
router.get('/:id', getProjectById);
router.get('/:id/analytics', getProjectAnalytics);
router.post('/', authorize('admin', 'project_manager', 'team_lead'), createProject);
router.patch('/:id', authorize('admin', 'project_manager', 'team_lead', 'manager'), updateProject);
router.delete('/:id', authorize('admin'), deleteProject);
router.patch('/:id/launch', authorize('admin', 'project_manager'), markLaunched);
router.patch('/:id/deliver', authorize('admin', 'project_manager'), markDelivered);
router.get('/:projectId/resources', resourceController.getResources);
router.post('/:projectId/resources', authorize('admin', 'project_manager', 'team_lead'), upload.single('file'), resourceController.addResource);
router.patch('/:projectId/resources/:id', authorize('admin', 'project_manager', 'team_lead'), upload.single('file'), resourceController.updateResource);
router.delete('/:projectId/resources/:id', authorize('admin', 'project_manager', 'team_lead'), resourceController.deleteResource);
router.get('/:projectId/team', teamController.getMembers);
router.post('/:projectId/team', authorize('admin', 'project_manager', 'team_lead'), teamController.addMember);
router.patch('/:projectId/team/:memberId', authorize('admin', 'project_manager', 'team_lead'), teamController.updateMemberRole);
router.delete('/:projectId/team/:memberId', authorize('admin', 'project_manager', 'team_lead'), teamController.removeMember);
router.get('/:projectId/team/assign', teamController.getProjectMembersForAssign);
router.get('/:projectId/team/analytics', analyticsController.getProjectTeamAnalytics);
router.get('/:projectId/team/groups', teamGroupController.getGroups);
router.post('/:projectId/team/groups', authorize('admin', 'project_manager', 'team_lead'), teamGroupController.createGroup);
router.patch('/:projectId/team/groups/:groupId', authorize('admin', 'project_manager', 'team_lead'), teamGroupController.updateGroup);
router.delete('/:projectId/team/groups/:groupId', authorize('admin', 'project_manager', 'team_lead'), teamGroupController.archiveGroup);
router.get('/teams/grouped', authorize('admin', 'project_manager', 'team_lead'), teamGroupController.getAllDomainGrouped);
router.get('/:projectId/team/grouped', teamGroupController.getGroupedMembers);
router.post('/:projectId/team/accept/:token', teamController.acceptInvitation);
router.post('/:projectId/team/decline/:token', teamController.declineInvitation);
router.get('/:projectId/settings', authorize('admin', 'project_manager', 'team_lead'), settingsController.getSettings);
router.put('/:projectId/settings', authorize('admin', 'project_manager', 'team_lead'), settingsController.updateSettings);
router.post('/:id/teams-channel', authorize('admin', 'project_manager', 'team_lead'), createTeamsChannel);
router.post('/:id/evaluate-phase', authorize('admin', 'project_manager', 'team_lead'), evaluatePhase);
module.exports = router;
