const { Router } = require('express');
const c = require('../controllers/sprintController');
const { auth, authorize } = require('../middleware/auth');
const r = Router();
r.use(auth);
r.get('/', c.getSprints);
r.get('/:id', c.getSprintById);
r.post('/', authorize('admin', 'project_manager', 'team_lead'), c.createSprint);
r.patch('/:id', c.updateSprint);
r.post('/:id/tasks', authorize('admin', 'project_manager', 'team_lead'), c.addTaskToSprint);
r.delete('/:id/tasks/:taskId', authorize('admin', 'project_manager', 'team_lead'), c.removeTaskFromSprint);
r.delete('/:id', authorize('admin'), c.deleteSprint);
module.exports = r;
