import { useState, useEffect, useCallback } from 'react';
import { useParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import { useAuth } from '../context/AuthContext';
import { testCases, interests, bugs, projects } from '../services/api';
import TestRunner from '../components/TestRunner';

const ALL_STATUSES = ['draft', 'auto-draft', 'ready', 'in_progress', 'passed', 'failed', 'blocked', 'skipped', 'retesting'];

const TABS = [
  { key: 'all', label: 'All Tests', icon: '📋' },
  { key: 'auto', label: 'Auto-Generated', icon: '🤖' },
  { key: 'flagged', label: 'Flagged', icon: '🚩' },
  { key: 'bugs', label: 'Bugs', icon: '🐛' },
  { key: 'config', label: 'Interest Config', icon: '⚙️' },
];

const STATUS_CLASS = {
  draft: 'tb-todo',
  'auto-draft': 'tb-todo',
  ready: 'tb-ip',
  in_progress: 'tb-ip',
  retesting: 'tb-rv',
  passed: 'tb-dn',
  failed: 'tb-dl',
  blocked: 'tb-rv',
  skipped: 'tb-todo',
};

const SEVERITY_CLS = {
  critical: 'tp-u',
  high: 'tp-h',
  medium: 'tp-m',
  low: 'tp-l',
};

const BUG_STATUS_CLS = {
  open: 'tb-dl',
  in_progress: 'tb-ip',
  fixed: 'tb-rv',
  closed: 'tb-dn',
  reopened: 'tb-dl',
};

export default function TestCaseDashboard() {
  const { projectId: urlProjectId } = useParams();
  const { user, socket } = useAuth();
  const isManager = ['admin', 'project_manager', 'team_lead', 'qa_tester'].includes(user?.role);
  const isAdmin = user?.role === 'admin';
  const canEdit = ['admin', 'project_manager', 'team_lead', 'manager', 'qa_tester'].includes(user?.role);

  const [activeTab, setActiveTab] = useState('all');
  const [projectList, setProjectList] = useState([]);
  const [selectedProject, setSelectedProject] = useState(urlProjectId || '');
  const [loading, setLoading] = useState(false);
  const [testList, setTestList] = useState([]);
  const [autoList, setAutoList] = useState([]);
  const [flaggedList, setFlaggedList] = useState([]);
  const [bugList, setBugList] = useState([]);
  const [interestConfig, setInterestConfig] = useState({ interestTags: [], priorityFeatures: [], ignorePatterns: [], autoDeleteEnabled: true, autoDeleteDays: 7 });
  const [stats, setStats] = useState(null);
  const [bugStats, setBugStats] = useState(null);
  const [testToRun, setTestToRun] = useState(null);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [editTest, setEditTest] = useState(null);
  const [editStatus, setEditStatus] = useState('');
  const [editAssignee, setEditAssignee] = useState('');
  const [qaMembers, setQaMembers] = useState([]);
  const [showNewForm, setShowNewForm] = useState(false);
  const [newForm, setNewForm] = useState({ title: '', description: '', type: 'manual', priority: 'medium' });

  useEffect(() => {
    projects.getAll().then(res => setProjectList(res.data)).catch(() => {});
  }, []);

  const fetchData = useCallback(async () => {
    if (!selectedProject) return;
    setLoading(true);
    try {
      const params = { project: selectedProject };
      const [testsRes, autoRes, flaggedRes, bugsRes, statsRes, bugStatsRes, interestRes] = await Promise.all([
        testCases.getAll(params).catch(() => ({ data: [] })),
        testCases.getAutoGenerated(selectedProject).catch(() => ({ data: [] })),
        interests.getFlagged(selectedProject).catch(() => ({ data: [] })),
        bugs.getAll({ projectId: selectedProject }).catch(() => ({ data: [] })),
        testCases.getStats(selectedProject).catch(() => null),
        bugs.getStats(selectedProject).catch(() => null),
        interests.getProjectInterests(selectedProject).catch(() => null),
      ]);
      setTestList(testsRes.data);
      setAutoList(autoRes.data);
      setFlaggedList(flaggedRes.data);
      setBugList(bugsRes.data);
      setStats(statsRes?.data);
      setBugStats(bugStatsRes?.data);
      if (interestRes?.data) {
        setInterestConfig({
          interestTags: interestRes.data.interestTags || [],
          priorityFeatures: interestRes.data.priorityFeatures || [],
          ignorePatterns: interestRes.data.ignorePatterns || [],
          autoDeleteEnabled: interestRes.data.autoDeleteEnabled ?? true,
          autoDeleteDays: interestRes.data.autoDeleteDays || 7,
        });
      }
    } catch (e) { toast.error('Failed to load data'); }
    setLoading(false);
  }, [selectedProject]);

  useEffect(() => { fetchData(); }, [fetchData]);

  // Socket: listen for test case events across the project
  useEffect(() => {
    if (!socket || !selectedProject) return;
    socket.emit('join_project', selectedProject);

    const refresh = () => fetchData();

    socket.on('test_case_created', refresh);
    socket.on('test_case_updated', refresh);
    socket.on('test_case_executed', refresh);
    socket.on('test_case_deleted', refresh);
    socket.on('test_cases_bulk_created', refresh);
    socket.on('test_cases_auto_generated', refresh);

    return () => {
      socket.emit('leave_project', selectedProject);
      socket.off('test_case_created', refresh);
      socket.off('test_case_updated', refresh);
      socket.off('test_case_executed', refresh);
      socket.off('test_case_deleted', refresh);
      socket.off('test_cases_bulk_created', refresh);
      socket.off('test_cases_auto_generated', refresh);
    };
  }, [socket, selectedProject]);

  const handleNewTest = async () => {
    if (!newForm.title.trim()) return toast.error('Title is required');
    try {
      await testCases.create({ ...newForm, project: selectedProject });
      toast.success('Test case created');
      setShowNewForm(false);
      setNewForm({ title: '', description: '', type: 'manual', priority: 'medium' });
      fetchData();
    } catch (e) {
      toast.error(e.response?.data?.message || 'Failed to create test case');
    }
  };

  const handleGenerateTests = async () => {
    if (!selectedProject) return toast.error('Select a project first');
    try {
      const res = await testCases.autoGenerate({ project: selectedProject });
      toast.success(`Generated ${res.data.length} test cases`);
      fetchData();
    } catch (e) {
      const msg = e.response?.data?.message || 'Generation failed';
      if (msg.includes('No tasks')) toast.error('No tasks found to generate from');
      else toast.error(msg);
    }
  };

  const handleGenerateCompleted = async () => {
    if (!selectedProject) return toast.error('Select a project first');
    try {
      const res = await testCases.generateCompleted({ projectId: selectedProject });
      toast.success(res.data.message);
      fetchData();
    } catch (e) {
      toast.error(e.response?.data?.message || 'Failed');
    }
  };

  const handleRunFilter = async () => {
    if (!selectedProject) return;
    try {
      const res = await interests.runFilter(selectedProject);
      toast.success(`Filter applied: ${res.data.flagged} flagged`);
      fetchData();
    } catch (e) { toast.error('Filter failed'); }
  };

  const handleRestoreFlagged = async (id) => {
    try {
      await interests.restoreFlagged(id);
      toast.success('Test case restored');
      fetchData();
    } catch (e) { toast.error('Restore failed'); }
  };

  const handleRestoreAll = async () => {
    try {
      const res = await interests.restoreAllFlagged();
      toast.success(`Restored ${res.data.count} test cases`);
      fetchData();
    } catch (e) { toast.error('Restore failed'); }
  };

  const handleDeleteAllFlagged = async () => {
    try {
      const res = await interests.deleteAllFlagged();
      toast.success(`Deleted ${res.data.count} test cases`);
      setShowDeleteConfirm(false);
      fetchData();
    } catch (e) { toast.error('Delete failed'); }
  };

  const handleSaveInterestConfig = async () => {
    if (!selectedProject) return;
    try {
      await interests.updateProjectInterests(selectedProject, interestConfig);
      toast.success('Interest config saved');
      fetchData();
    } catch (e) { toast.error('Save failed'); }
  };

  const handleResolveBug = async (bugId) => {
    const notes = prompt('Resolution notes:');
    if (notes === null) return;
    try {
      await bugs.resolve(bugId, { resolutionNotes: notes || 'Resolved' });
      toast.success('Bug resolved');
      fetchData();
    } catch (e) { toast.error('Resolve failed'); }
  };

  const handleReopenBug = async (bugId) => {
    const reason = prompt('Failure reason for retest:');
    if (reason === null) return;
    try {
      await bugs.reopen(bugId, { failureReason: reason || 'Retest failed' });
      toast.success('Bug reopened');
      fetchData();
    } catch (e) { toast.error('Reopen failed'); }
  };

  const handleDeleteTest = async (id) => {
    if (!window.confirm('Delete this test case?')) return;
    try {
      await testCases.delete(id);
      toast.success('Test case deleted');
      fetchData();
    } catch (e) { toast.error('Delete failed'); }
  };

  const handleRetestTest = async (id) => {
    try {
      await testCases.retest(id);
      toast.success('Test reset for retesting');
      fetchData();
    } catch (e) { toast.error('Retest failed'); }
  };

  const handleOpenEdit = async (tc) => {
    setEditStatus(tc.status);
    setEditAssignee(tc.assignee?._id || '');
    setEditTest(tc);
    try {
      const res = await projects.getTeam(selectedProject);
      const members = Array.isArray(res.data) ? res.data : res.data?.members || [];
      setQaMembers(members.filter(m => m.projectRole === 'qa_tester' && m.status === 'active'));
    } catch (e) { setQaMembers([]); }
  };

  const handleSaveEdit = async () => {
    if (!editTest) return;
    try {
      const data = {};
      if (editStatus !== editTest.status) data.status = editStatus;
      const newAssigneeId = editAssignee || null;
      const oldAssigneeId = editTest.assignee?._id || null;
      if (newAssigneeId !== oldAssigneeId) data.assignee = newAssigneeId;
      if (Object.keys(data).length === 0) { setEditTest(null); return; }
      await testCases.update(editTest._id, data);
      toast.success('Test case updated');
      setEditTest(null);
      fetchData();
    } catch (e) { toast.error(e.response?.data?.message || 'Update failed'); }
  };

  if (!projectList.length && !selectedProject) {
    return (
      <div>
        <div style={{fontSize:18,fontWeight:700,color:'#111827',marginBottom:12}}>🧪 Test Case Dashboard</div>
        <div className="card" style={{padding:'40px 20px',textAlign:'center'}}>
          <p style={{color:'#9ca3af',fontSize:12}}>No projects found.</p>
          <p style={{color:'#9ca3af',fontSize:11,marginTop:4}}>Create a project to start managing test cases.</p>
        </div>
      </div>
    );
  }

  return (
    <div>
      <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:12}}>
        <div>
          <div style={{fontSize:18,fontWeight:700,color:'#111827'}}>🧪 Test Case Dashboard</div>
          <div style={{fontSize:11,color:'#9ca3af',marginTop:1}}>{testList.length} test cases</div>
        </div>
        <select value={selectedProject} onChange={e => setSelectedProject(e.target.value)}
          style={{padding:'5px 8px',border:'0.5px solid #e5e7eb',borderRadius:6,fontSize:11,background:'#f9fafb',outline:'none',minWidth:180}}>
          <option value="">Select a project...</option>
          {projectList.map(p => <option key={p._id} value={p._id}>{p.name}</option>)}
        </select>
      </div>

      {!selectedProject ? (
        <div className="card" style={{padding:'40px 20px',textAlign:'center'}}>
          <p style={{color:'#9ca3af',fontSize:12}}>Select a project to view its test cases.</p>
        </div>
      ) : (
        <>
          {stats && (
            <div className="stats-grid" style={{gridTemplateColumns:'repeat(5,1fr)'}}>
              <div className="stat-pill"><div className="sp-n">{stats.total}</div><div className="sp-l">Total</div></div>
              <div className="stat-pill"><div className="sp-n" style={{color:'#15803d'}}>{stats.passRate}%</div><div className="sp-l">Pass Rate</div></div>
              <div className="stat-pill"><div className="sp-n" style={{color:'#1d4ed8'}}>{stats.coverage}%</div><div className="sp-l">Coverage</div></div>
              <div className="stat-pill"><div className="sp-n" style={{color:'#15803d'}}>{stats.passed}</div><div className="sp-l">Passed</div></div>
              <div className="stat-pill"><div className="sp-n" style={{color:'#b91c1c'}}>{stats.failed}</div><div className="sp-l">Failed</div></div>
            </div>
          )}

          {/* Tabs */}
          <div className="card" style={{padding:0,marginBottom:12,overflow:'hidden'}}>
            <div className="tabs" style={{background:'transparent',padding:0}}>
              {TABS.map(tab => (
                <div key={tab.key} onClick={() => setActiveTab(tab.key)}
                  className={`tab ${activeTab === tab.key ? 'active' : ''}`}
                  style={{fontSize:11,padding:'8px 12px'}}>
                  {tab.icon} {tab.label}
                </div>
              ))}
            </div>
          </div>

          {/* Tab Content */}
          <div className="card" style={{padding:'14px 16px'}}>
            {loading ? (
              <div style={{textAlign:'center',padding:'30px 0',color:'#9ca3af',fontSize:11}}>Loading...</div>
            ) : activeTab === 'all' ? renderAllTests() : activeTab === 'auto' ? renderAutoTests() : activeTab === 'flagged' ? renderFlaggedTests() : activeTab === 'bugs' ? renderBugs() : renderConfig()}
          </div>
        </>
      )}

      {testToRun && (
        <TestRunner testCase={testToRun} onClose={() => setTestToRun(null)} onComplete={fetchData} />
      )}

      {showDeleteConfirm && (
        <div style={{position:'fixed',inset:0,background:'rgba(0,0,0,0.45)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:10000}} onClick={() => setShowDeleteConfirm(false)}>
          <div className="card" style={{padding:20,maxWidth:360,width:'90%'}} onClick={e => e.stopPropagation()}>
            <h3 style={{fontSize:13,fontWeight:700,color:'#111827',margin:'0 0 6px'}}>Delete All Flagged Tests?</h3>
            <p style={{fontSize:11,color:'#6b7280',margin:'0 0 14px'}}>This action cannot be undone. {flaggedList.length} test cases will be permanently deleted.</p>
            <div style={{display:'flex',gap:6,justifyContent:'flex-end'}}>
              <button className="btn btn-gray" onClick={() => setShowDeleteConfirm(false)}>Cancel</button>
              <button className="btn" style={{background:'#b91c1c',color:'white'}} onClick={handleDeleteAllFlagged}>Delete All</button>
            </div>
          </div>
        </div>
      )}

      {showNewForm && (
        <div style={{position:'fixed',inset:0,background:'rgba(0,0,0,0.45)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:10000}} onClick={() => { setShowNewForm(false); setNewForm({ title: '', description: '', type: 'manual', priority: 'medium' }); }}>
          <div className="card" style={{padding:20,maxWidth:420,width:'90%'}} onClick={e => e.stopPropagation()}>
            <h3 style={{fontSize:13,fontWeight:700,color:'#111827',margin:'0 0 14px'}}>+ New Test Case</h3>
            <div style={{display:'flex',flexDirection:'column',gap:10}}>
              <div>
                <label style={{fontSize:10,fontWeight:500,color:'#6b7280',display:'block',marginBottom:3}}>Title *</label>
                <input className="finput" style={{width:'100%'}} value={newForm.title}
                  onChange={e => setNewForm({...newForm, title: e.target.value})} placeholder="Test case title" />
              </div>
              <div>
                <label style={{fontSize:10,fontWeight:500,color:'#6b7280',display:'block',marginBottom:3}}>Description</label>
                <textarea className="finput" style={{width:'100%',resize:'vertical',minHeight:50}} value={newForm.description}
                  onChange={e => setNewForm({...newForm, description: e.target.value})} placeholder="Optional description" />
              </div>
              <div style={{display:'flex',gap:10}}>
                <div style={{flex:1}}>
                  <label style={{fontSize:10,fontWeight:500,color:'#6b7280',display:'block',marginBottom:3}}>Type</label>
                  <select value={newForm.type} onChange={e => setNewForm({...newForm, type: e.target.value})}
                    style={{width:'100%',padding:'6px 8px',border:'0.5px solid #e5e7eb',borderRadius:6,fontSize:11,background:'#f9fafb',outline:'none'}}>
                    {['manual','integration','unit','e2e','security','performance'].map(t => <option key={t} value={t}>{t}</option>)}
                  </select>
                </div>
                <div style={{flex:1}}>
                  <label style={{fontSize:10,fontWeight:500,color:'#6b7280',display:'block',marginBottom:3}}>Priority</label>
                  <select value={newForm.priority} onChange={e => setNewForm({...newForm, priority: e.target.value})}
                    style={{width:'100%',padding:'6px 8px',border:'0.5px solid #e5e7eb',borderRadius:6,fontSize:11,background:'#f9fafb',outline:'none'}}>
                    {['low','medium','high','urgent','critical'].map(p => <option key={p} value={p}>{p}</option>)}
                  </select>
                </div>
              </div>
            </div>
            <div style={{display:'flex',gap:6,justifyContent:'flex-end',marginTop:14}}>
              <button className="btn btn-gray" onClick={() => { setShowNewForm(false); setNewForm({ title: '', description: '', type: 'manual', priority: 'medium' }); }}>Cancel</button>
              <button className="btn btn-green" onClick={handleNewTest}>+ Create</button>
            </div>
          </div>
        </div>
      )}

      {editTest && (
        <div style={{position:'fixed',inset:0,background:'rgba(0,0,0,0.45)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:10000}} onClick={() => setEditTest(null)}>
          <div className="card" style={{padding:20,maxWidth:400,width:'90%'}} onClick={e => e.stopPropagation()}>
            <h3 style={{fontSize:13,fontWeight:700,color:'#111827',margin:'0 0 4px'}}>✏️ Edit Test Case</h3>
            <p style={{fontSize:11,color:'#6b7280',margin:'0 0 14px'}}>{editTest.testCaseId} — {editTest.title}</p>
            <div style={{display:'flex',flexDirection:'column',gap:10}}>
              <div>
                <label style={{fontSize:10,fontWeight:500,color:'#6b7280',display:'block',marginBottom:3}}>Status</label>
                <select value={editStatus} onChange={e => setEditStatus(e.target.value)}
                  style={{width:'100%',padding:'6px 8px',border:'0.5px solid #e5e7eb',borderRadius:6,fontSize:11,background:'#f9fafb',outline:'none'}}>
                  {ALL_STATUSES.map(s => <option key={s} value={s}>{s}</option>)}
                </select>
              </div>
              <div>
                <label style={{fontSize:10,fontWeight:500,color:'#6b7280',display:'block',marginBottom:3}}>Assign to QA Tester</label>
                <select value={editAssignee} onChange={e => setEditAssignee(e.target.value)}
                  style={{width:'100%',padding:'6px 8px',border:'0.5px solid #e5e7eb',borderRadius:6,fontSize:11,background:'#f9fafb',outline:'none'}}>
                  <option value="">Unassigned</option>
                  {qaMembers.map(m => (
                    <option key={m.user?._id} value={m.user?._id}>
                      {m.user?.name || m.user?.email}
                    </option>
                  ))}
                </select>
              </div>
            </div>
            <div style={{display:'flex',gap:6,justifyContent:'flex-end',marginTop:14}}>
              <button className="btn btn-gray" onClick={() => setEditTest(null)}>Cancel</button>
              <button className="btn btn-blue" onClick={handleSaveEdit}>💾 Save</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );

  function renderAllTests() {
    return (
      <div>
        <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:10}}>
          <div style={{fontSize:12,fontWeight:600,color:'#111827'}}>All Test Cases ({testList.length})</div>
          <div style={{display:'flex',gap:6}}>
            {canEdit && <button className="btn btn-green" onClick={() => setShowNewForm(true)} style={{fontSize:10}}>+ New Test Case</button>}
            {canEdit && <button className="btn btn-blue" onClick={handleGenerateTests} style={{fontSize:10}}>🤖 Generate from Tasks</button>}
            {canEdit && <button className="btn btn-amber" onClick={handleGenerateCompleted} style={{fontSize:10}}>📦 From Completed Sprints</button>}
          </div>
        </div>
        {testList.length === 0 ? (
          <div style={{textAlign:'center',padding:'30px 0',color:'#9ca3af',fontSize:11}}>No test cases yet.</div>
        ) : (
          <div style={{border:'0.5px solid #e5e7eb',borderRadius:8,overflow:'hidden'}}>
            {testList.map(tc => (
              <div key={tc._id} className="task-row">
                <div style={{flex:1,minWidth:0}}>
                  <div style={{display:'flex',alignItems:'center',gap:6}}>
                    <span className={`tbadge ${STATUS_CLASS[tc.status] || 'tb-todo'}`}>{tc.status}</span>
                    <span className="t-title" style={{fontSize:11}}>{tc.testCaseId} — {tc.title}</span>
                    {tc.autoGenerated && <span className="tbadge tb-todo" style={{fontSize:8}}>auto</span>}
                  </div>
                  <div style={{fontSize:10,color:'#9ca3af',marginTop:2}}>
                    {tc.feature && <>{tc.feature} · </>}
                    <span style={{color:'#6b7280',fontWeight:500}}>{tc.priority}</span> · {tc.type}
                    {tc.assignee && <> · {tc.assignee.name}</>}
                  </div>
                </div>
                <div style={{display:'flex',gap:4,flexShrink:0}}>
                  {isManager && ['ready', 'in_progress', 'retesting'].includes(tc.status) && (
                    <button className="btn btn-green" style={{fontSize:9,padding:'3px 8px'}} onClick={() => setTestToRun(tc)}>▶ Run</button>
                  )}
                  {tc.status === 'failed' && (
                    <button className="btn btn-amber" style={{fontSize:9,padding:'3px 8px'}} onClick={() => handleRetestTest(tc._id)}>🔄 Retest</button>
                  )}
                  {canEdit && (
                    <button className="btn btn-red" style={{fontSize:9,padding:'3px 8px'}} onClick={() => handleDeleteTest(tc._id)}>🗑</button>
                  )}
                  {canEdit && (
                  <button className="btn btn-gray" style={{fontSize:9,padding:'3px 8px'}} onClick={() => handleOpenEdit(tc)}>Edit</button>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    );
  }

  function renderAutoTests() {
    return (
      <div>
        <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:10}}>
          <div style={{fontSize:12,fontWeight:600,color:'#111827'}}>Auto-Generated Tests ({autoList.length})</div>
          <div style={{display:'flex',gap:6}}>
            {canEdit && <button className="btn btn-amber" onClick={handleRunFilter} style={{fontSize:10}}>🚩 Run Interest Filter</button>}
          </div>
        </div>
        {autoList.length === 0 ? (
          <div style={{textAlign:'center',padding:'30px 0',color:'#9ca3af',fontSize:11}}>No auto-generated tests. Click "Generate from Tasks" to create.</div>
        ) : (
          <div style={{border:'0.5px solid #e5e7eb',borderRadius:8,overflow:'hidden'}}>
            {autoList.map(tc => (
              <div key={tc._id} className="task-row">
                <div style={{flex:1,minWidth:0}}>
                  <div style={{display:'flex',alignItems:'center',gap:6}}>
                    <span className={`tbadge ${STATUS_CLASS[tc.status] || 'tb-todo'}`}>{tc.status}</span>
                    <span className="t-title" style={{fontSize:11}}>{tc.testCaseId} — {tc.title}</span>
                    <span className="tbadge" style={{
                      background: tc.interestMatchStatus === 'high' ? '#f0fdf4' : tc.interestMatchStatus === 'low' ? '#fffbeb' : '#fff1f2',
                      color: tc.interestMatchStatus === 'high' ? '#15803d' : tc.interestMatchStatus === 'low' ? '#b45309' : '#b91c1c',
                    }}>{tc.interestMatchScore}%</span>
                  </div>
                  <div style={{fontSize:10,color:'#9ca3af',marginTop:2}}>
                    Match: {tc.interestMatchStatus} · Linked: {tc.linkedTask?.title || 'none'}
                  </div>
                </div>
                <div style={{display:'flex',gap:4,flexShrink:0}}>
                  {isManager && ['ready', 'in_progress'].includes(tc.status) && (
                    <button className="btn btn-green" style={{fontSize:9,padding:'3px 8px'}} onClick={() => setTestToRun(tc)}>▶ Run</button>
                  )}
                  {canEdit && (
                  <button className="btn btn-gray" style={{fontSize:9,padding:'3px 8px'}} onClick={() => handleOpenEdit(tc)}>Edit</button>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    );
  }

  function renderFlaggedTests() {
    return (
      <div>
        <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:10}}>
          <div style={{fontSize:12,fontWeight:600,color:'#111827'}}>🚩 Flagged for Deletion ({flaggedList.length})</div>
          <div style={{display:'flex',gap:6}}>
            {flaggedList.length > 0 && (
              <>
                <button className="btn btn-green" style={{fontSize:10}} onClick={handleRestoreAll}>Restore All</button>
                {isAdmin && <button className="btn btn-red" style={{fontSize:10}} onClick={() => setShowDeleteConfirm(true)}>Delete All</button>}
              </>
            )}
          </div>
        </div>
        {flaggedList.length === 0 ? (
          <div style={{textAlign:'center',padding:'30px 0',color:'#9ca3af',fontSize:11}}>No flagged test cases.</div>
        ) : (
          <div style={{border:'0.5px solid #e5e7eb',borderRadius:8,overflow:'hidden'}}>
            {flaggedList.map(tc => (
              <div key={tc._id} className="task-row" style={{borderLeft:'3px solid #ef4444'}}>
                <div style={{flex:1,minWidth:0}}>
                  <div style={{display:'flex',alignItems:'center',gap:6}}>
                    <span className="tbadge tb-dl">{tc.interestMatchScore}% match</span>
                    <span className="t-title" style={{fontSize:11}}>{tc.testCaseId} — {tc.title}</span>
                  </div>
                  <div style={{fontSize:10,color:'#9ca3af',marginTop:2}}>
                    Auto-delete: {tc.autoDeleteAt ? new Date(tc.autoDeleteAt).toLocaleDateString() : 'N/A'}
                    {tc.sprint && <> · Sprint: {tc.sprint.name}</>}
                  </div>
                </div>
                <div style={{display:'flex',gap:4,flexShrink:0}}>
                  <button className="btn btn-green" style={{fontSize:9,padding:'3px 8px'}} onClick={() => handleRestoreFlagged(tc._id)}>↩ Restore</button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    );
  }

  function renderBugs() {
    return (
      <div>
        {bugStats && (
          <div className="stats-grid" style={{gridTemplateColumns:'repeat(6,1fr)',marginBottom:10}}>
            <div className="stat-pill"><div className="sp-n">{bugStats.total}</div><div className="sp-l">Total</div></div>
            <div className="stat-pill"><div className="sp-n" style={{color:'#b91c1c'}}>{bugStats.open}</div><div className="sp-l">Open</div></div>
            <div className="stat-pill"><div className="sp-n" style={{color:'#b45309'}}>{bugStats.inProgress}</div><div className="sp-l">In Progress</div></div>
            <div className="stat-pill"><div className="sp-n" style={{color:'#15803d'}}>{bugStats.closed}</div><div className="sp-l">Closed</div></div>
            <div className="stat-pill"><div className="sp-n" style={{color:'#b91c1c'}}>{bugStats.critical}</div><div className="sp-l">Critical</div></div>
            <div className="stat-pill"><div className="sp-n" style={{color:'#c2410c'}}>{bugStats.reopened}</div><div className="sp-l">Reopened</div></div>
          </div>
        )}
        <div style={{fontSize:12,fontWeight:600,color:'#111827',marginBottom:8}}>Bugs ({bugList.length})</div>
        {bugList.length === 0 ? (
          <div style={{textAlign:'center',padding:'30px 0',color:'#9ca3af',fontSize:11}}>No bugs from test failures.</div>
        ) : (
          <div style={{border:'0.5px solid #e5e7eb',borderRadius:8,overflow:'hidden'}}>
            {bugList.map(bug => (
              <div key={bug._id} className="task-row">
                <div style={{flex:1,minWidth:0}}>
                  <div style={{display:'flex',alignItems:'center',gap:6}}>
                    <span className={`tbadge ${bug.status === 'open' ? 'tb-dl' : bug.status === 'in_progress' ? 'tb-ip' : bug.status === 'fixed' ? 'tb-rv' : bug.status === 'closed' ? 'tb-dn' : 'tb-dl'}`}>{bug.status}</span>
                    <span className={`tpriority ${SEVERITY_CLS[bug.severity] || 'tp-m'}`} style={{fontSize:10}}>{bug.severity}</span>
                    <span className="t-title" style={{fontSize:11}}>{bug.title}</span>
                  </div>
                  <div style={{fontSize:10,color:'#9ca3af',marginTop:2}}>
                    {bug.testCase?.testCaseId && <>From: {bug.testCase.testCaseId} · </>}
                    Assignee: {bug.assignee?.name || 'unassigned'}
                    {bug.retestCount > 0 && <> · Retests: {bug.retestCount}</>}
                  </div>
                </div>
                <div style={{display:'flex',gap:4,flexShrink:0}}>
                  {bug.status === 'open' && canEdit && (
                    <button className="btn btn-green" style={{fontSize:9,padding:'3px 8px'}} onClick={() => handleResolveBug(bug._id)}>✅ Resolve</button>
                  )}
                  {bug.status === 'closed' && isManager && (
                    <button className="btn btn-amber" style={{fontSize:9,padding:'3px 8px'}} onClick={() => handleReopenBug(bug._id)}>🔄 Reopen</button>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    );
  }

  function renderConfig() {
    const tagify = (val) => val.split(',').map(s => s.trim()).filter(Boolean);
    return (
      <div>
        <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:10}}>
          <div style={{fontSize:12,fontWeight:600,color:'#111827'}}>⚙️ Interest Configuration</div>
          {canEdit && <button className="btn btn-blue" style={{fontSize:10}} onClick={handleSaveInterestConfig}>💾 Save</button>}
        </div>
        <div style={{maxWidth:480,display:'flex',flexDirection:'column',gap:10}}>
          <div>
            <label style={{fontSize:10,fontWeight:500,color:'#6b7280',display:'block',marginBottom:3}}>Interest Tags</label>
            <input className="finput" style={{width:'100%'}} value={interestConfig.interestTags.join(', ')}
              onChange={e => setInterestConfig({...interestConfig, interestTags: tagify(e.target.value)})}
              disabled={!canEdit} placeholder="e.g. payment, auth, dashboard" />
          </div>
          <div>
            <label style={{fontSize:10,fontWeight:500,color:'#6b7280',display:'block',marginBottom:3}}>Priority Features</label>
            <input className="finput" style={{width:'100%'}} value={interestConfig.priorityFeatures.join(', ')}
              onChange={e => setInterestConfig({...interestConfig, priorityFeatures: tagify(e.target.value)})}
              disabled={!canEdit} placeholder="e.g. checkout, login, payment" />
          </div>
          <div>
            <label style={{fontSize:10,fontWeight:500,color:'#6b7280',display:'block',marginBottom:3}}>Ignore Patterns</label>
            <input className="finput" style={{width:'100%'}} value={interestConfig.ignorePatterns.join(', ')}
              onChange={e => setInterestConfig({...interestConfig, ignorePatterns: tagify(e.target.value)})}
              disabled={!canEdit} placeholder="e.g. legacy, deprecated, ui-only" />
          </div>
          <div style={{display:'flex',alignItems:'center',gap:12}}>
            <label style={{display:'flex',alignItems:'center',gap:6,fontSize:11,color:'#374151',cursor:'pointer'}}>
              <input type="checkbox" checked={interestConfig.autoDeleteEnabled}
                onChange={e => setInterestConfig({...interestConfig, autoDeleteEnabled: e.target.checked})}
                disabled={!canEdit} />
              Auto-delete enabled
            </label>
            {interestConfig.autoDeleteEnabled && (
              <div style={{display:'flex',alignItems:'center',gap:6}}>
                <span style={{fontSize:10,color:'#6b7280'}}>Delete after</span>
                <input type="number" min={1} max={30} value={interestConfig.autoDeleteDays}
                  onChange={e => setInterestConfig({...interestConfig, autoDeleteDays: parseInt(e.target.value) || 7})}
                  disabled={!canEdit}
                  style={{width:50,textAlign:'center',padding:'4px 6px',border:'0.5px solid #e5e7eb',borderRadius:5,fontSize:10,background:'#f9fafb',outline:'none'}} />
                <span style={{fontSize:10,color:'#9ca3af'}}>days</span>
              </div>
            )}
          </div>
          {canEdit && <button className="btn btn-amber" style={{fontSize:10,alignSelf:'flex-start'}} onClick={handleRunFilter}>🚩 Apply Interest Filter Now</button>}
        </div>
      </div>
    );
  }
}
